# Imagen base
FROM node:18

# Directorio de trabajo dentro del contenedor
WORKDIR /app

# Copia package.json y lockfile para instalar dependencias
COPY package*.json ./

# Instala dependencias
RUN npm install

# Copia el resto de los archivos
COPY . .

# Expone el puerto de Vite
EXPOSE 5173

# Comando para iniciar la app
CMD ["npm", "run", "dev"]
