# Imagen base de Node
FROM node:18

# Crear directorio de trabajo dentro del contenedor
WORKDIR /app

# Copiar package.json y package-lock.json (si existe)
COPY package*.json ./

# Instalar dependencias
RUN npm install

# Copiar el resto del código al contenedor
COPY . .

# Exponer el puerto (asegúrate que tu backend corre en este)
EXPOSE 3000

# Comando por defecto
CMD ["npm", "run", "dev"]
